version: 2.1

env:
  global:
    VERSION: "build-$CIRCLE_BUILD_NUM"

jobs:
  build_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lets build and push 
          command: |
            docker build -t ankitjodhani/tic-tac-toe:$VERSION .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push ankitjodhani/tic-tac-toe:$VERSION

  publish:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: we are just testing it 
          command: |
            git clone https://github.com/AnkitJodhani/temp2.git
            git config --global user.email "ankitjodhani1903@gmail.com"
            git config --global user.name "AnkitJodhani"
            cd temp2
            sed -i "s/build-[0-9]\+/$VERSION/g" menifest/deployment.yaml
            git add .
            git commit -m "new build with imgTAG build-$CIRCLE_BUILD_NUM"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/AnkitJodhani/temp2.git main 
workflows:
  GitOpsflow:
    jobs:
      - build_push
      - publish:
          requires:
            - build_push
      






  

  
