version: 2.1

jobs:
  test_git:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run:
          name: we are just testing it 
          command: |
            git clone https://github.com/AnkitJodhani/temp2.git
            git config --global user.email "ankitjodhani1903@gmail.com"
            git config --global user.name "AnkitJodhani"
            cd temp2
            sed -i "s/TAG/build-$CIRCLE_BUILD_NUM/g" deployment.yaml
            git add .
            git commit -m "new build with imgTAG build-$CIRCLE_BUILD_NUM"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/AnkitJodhani/temp2.git main 
workflows:
  testing:
    jobs:
      - test_git

  
